Various mods to How to Host that came to mind while I was setting up my event
GoogleCloudPlatform/cloud-hackathons pull request #30
Opened 2023-06-06 21:29 UTC by gfilicetti

2023-06-07 15:42 UTC, gfilicetti commented
One more change: changed attendee and student to "participant"

2023-06-07 15:59 UTC, meken requested changes

2023-06-07 15:59 UTC, meken commented on faq/howto-host-hack.md
> -You need to create _Classroom_ instances for every event you want to organize. A _Classroom_ has a start and an end date, references the _Classroom Template_ which determines the lab. You'll need to
I want this section back, unless we can automate the generation of the Classroom Template, we'll need these instructions.

2023-06-08 11:48 UTC, gfilicetti commented
Ok @meken ... I've reverted the Classroom Template instruction removal. Also added arrows to its screenshot.

2023-06-08 12:02 UTC, meken approved these changes

2023-06-08 12:02 UTC, merged