merge the gHack materials for gaming on gcp
GoogleCloudPlatform/cloud-hackathons pull request #43
Opened 2023-08-01 00:24 UTC by dw800

Please review and approve the pull request. Thank you!

2023-08-04 07:45 UTC, meken commented on hacks/gaming-on-gcp/QL_OWNER
> +danielnwang@google.com
As discussed, just need to make sure that either Daniel has author permissions on CE qwiklabs or we replace this with our names (as this is hidden anyway, the real contributor info is in the hack)

2023-08-04 07:46 UTC, meken commented on .DS_Store
Is it possible to get rid of these files? Not sure if they're needed. @gfilicetti note to ourselves to include .DS_Store in .gitignore, wdyt?

2023-08-04 17:03 UTC, gfilicetti commented on hacks/gaming-on-gcp/QL_OWNER
> +danielnwang@google.com
@dw800 Can you please change this to our new default which is this text making up the entire body of the file:

```
meken@google.com
# Collaborators
ginof@google.com
```

Only emails that are registered as Qwiklabs CE Authors can be in this file. Don't worry it's hidden, as Murat mentioned.

2023-08-08 22:14 UTC, gfilicetti requested changes
Amazing stuff Daniel! I love the detail in the coach's guide too.

Just a few things to consider here, let me know if you have questions.

2023-08-08 22:14 UTC, gfilicetti commented on hacks/gaming-on-gcp/README.md
> +- [Blog post: Player Churn Prediction with BigQuery ML](https://cloud.google.com/blog/topics/developers-practitioners/churn-prediction-game-developers-using-google-analytics-4-ga4-and-bigquery-ml)
Will this end up being a cut and paste exercise since we're telling them to follow steps in the blog post? Will they need to do any thinking?

2023-08-08 22:14 UTC, gfilicetti commented on hacks/gaming-on-gcp/solutions.md
> +Welcome to the coach's guide for Gaming in GCP. Here you will find links to specific guidance for coaches for each of the challenges.
Change to "Gaming on GCP"

2023-08-08 22:14 UTC, gfilicetti commented on hacks/gaming-on-gcp/solutions.md
> +### Student Resources
Since you are not providing any student resources, please delete this entire section.

2023-08-08 23:19 UTC, dw800 commented on hacks/gaming-on-gcp/QL_OWNER
> +danielnwang@google.com
Please feel free to replace with your emails.

2023-08-09 00:04 UTC, dw800 commented on .DS_Store
will do. Thank you!

2023-08-09 00:04 UTC, dw800 commented on hacks/gaming-on-gcp/images/.gitkeep
Got it. Thank you!

2023-08-09 00:04 UTC, dw800 commented on hacks/gaming-on-gcp/resources/template-lectures.pdf
Sure, thank you!

2023-08-09 00:07 UTC, dw800 commented on hacks/gaming-on-gcp/README.md
> +- Agones is successfully installed on the Kubernetes cluster.
Added, thank you!

2023-08-09 00:07 UTC, dw800 commented on hacks/gaming-on-gcp/README.md
> +- Agones is successfully installed on the Kubernetes cluster.
Good catch, updated.

2023-08-09 00:09 UTC, dw800 commented on hacks/gaming-on-gcp/README.md
> +Your task is to deploy Agones on a Kubernetes cluster in Google Cloud. Follow the steps below:
Sounds good. Thank you!

2023-08-09 00:10 UTC, dw800 commented on hacks/gaming-on-gcp/README.md
> +- Install Agones on the Kubernetes cluster. Use the provided Agones documentation to install the required components and configure Agones.
Updated, thank you!

2023-08-09 00:15 UTC, dw800 commented on hacks/gaming-on-gcp/README.md
> +- Create a simple game server deployment. Define a basic game server deployment using the Agones configuration. This will include specifying the game server image, ports, and other necessary paramete
ok, updated. Thank you!

2023-08-09 00:19 UTC, dw800 commented on hacks/gaming-on-gcp/README.md
> +- Test the deployment. Validate that the game server deployment is successful by checking the status of the pods and services created by Agones. Ensure that the game server is running and accessible.
Updated. Thank you!

2023-08-09 00:21 UTC, dw800 commented on hacks/gaming-on-gcp/README.md
> +- The game server is accessible and functioning as expected.
Added, thank you!

2023-08-09 00:23 UTC, dw800 commented on hacks/gaming-on-gcp/README.md
> +
Added. Thank you!

2023-08-09 00:27 UTC, dw800 commented on hacks/gaming-on-gcp/README.md
> +- [Blog post: Player Churn Prediction with BigQuery ML](https://cloud.google.com/blog/topics/developers-practitioners/churn-prediction-game-developers-using-google-analytics-4-ga4-and-bigquery-ml)
They will have to the basics of BigQuery to get it to work, not expecting them to be experts. Based on this example, they can think about how to apply it to their own datasets.

2023-08-09 00:29 UTC, dw800 commented on hacks/gaming-on-gcp/solutions.md
> +Welcome to the coach's guide for Gaming in GCP. Here you will find links to specific guidance for coaches for each of the challenges.
Updated, thank you!

2023-08-09 00:32 UTC, dw800 commented on hacks/gaming-on-gcp/solutions.md
> +### Student Resources
Removed. Thank you!

2023-08-11 22:03 UTC, gfilicetti approved these changes

2023-08-11 22:05 UTC, merged