New gHack - Modernizing Monoliths
GoogleCloudPlatform/cloud-hackathons pull request #69
Opened 2023-12-14 23:55 UTC by TheLanceLord

A gHack for learning Docker and GKE by writing a Dockerfile for and deploying a web game

2023-12-15 00:10 UTC, gfilicetti commented
Rendered site is here:

https://thelancelord.github.io/cloud-hackathons/

2023-12-19 09:50 UTC, meken commented on hacks/modernizing-monoliths/QL_OWNER
If you don't have author access on the ce.qwiklabs, either get access to it or use Gino's/mine ldap

2023-12-19 09:52 UTC, meken commented on hacks/modernizing-monoliths/solutions.md
> +# “Modernizing
Modernizing Monoliths with ascii quotes

2023-12-19 10:33 UTC, meken commented on hacks/modernizing-monoliths/solutions/challenge-1/Dockerfile.advanced
@gfilicetti do we keep these as separate files or just put in `solutions.md` as markdown blocks?

2023-12-19 10:33 UTC, meken commented on hacks/modernizing-monoliths/solutions/challenge-1/Dockerfile.advanced
@gfilicetti do we keep these as separate files or just put in `solutions.md` as markdown blocks?

2024-01-31 20:43 UTC, TheLanceLord commented
updates made! added Gino's ldap as I can't create a Qwiklabs account via the ce portal

2024-03-04 18:14 UTC, gfilicetti reviewed
Here's my first pass of comments and fixes. Ping me if you need clarifications.

2024-03-04 18:14 UTC, gfilicetti commented on hacks/modernizing-monoliths/solutions.md
> +Remember that this hack includes a optional [lecture presentation](resources/lecture.pdf) that features short presentations to introduce key topics associated with each challenge. It is recommended t
I think we shouldn't label the lectures as optional. Maybe just say: 

"Remember that this hack includes a lectures.pdf that features short presentations to introduce key topics...."

2024-03-04 18:14 UTC, gfilicetti commented on hacks/modernizing-monoliths/solutions.md
> +- `./images`
We're deleting this folder, so you can delete this bullet.

2024-03-04 18:14 UTC, gfilicetti commented on hacks/modernizing-monoliths/solutions.md
> +- Participant will need to download the [crawl repository](https://github.com/TheLanceLord/crawl) to their working environment and create their Dockerfile in the root folder of the repository
*Participants

2024-03-04 18:14 UTC, gfilicetti commented on hacks/modernizing-monoliths/solutions.md
> +## Challenge 3: Speedrun - containerize and deploy the load testing application
Please add a blank line above Challenge 3 header line.

2024-03-04 18:18 UTC, gfilicetti commented on hacks/modernizing-monoliths/solutions/challenge-1/Dockerfile.advanced
There are a lot of solutions files so I'd rather keep them separate. The relative links will make it easy for the coaches to jump to and fro.

2024-03-04 18:18 UTC, gfilicetti commented on hacks/modernizing-monoliths/solutions/challenge-1/Dockerfile.advanced
Same as above.

2024-03-18 23:22 UTC, TheLanceLord commented on hacks/modernizing-monoliths/README.md
> +- **Compiling DCSS with `make WEBTILES=y` command can take 25+ minutes**. Compile the code on your host machine and create your image from the compiled code to save time on your builds.
only if they want to do the advanced challenge, otherwise the gHack could easily take the entire day as people spend time waiting to see what libraries or packages their base image is missing for them to compile the application; someone experienced with writing Dockerfiles though could probably easily knock this out in 1-2 attempts, so a 25 minute compile time wouldn't be that problematic.

2024-03-18 23:36 UTC, TheLanceLord commented
Changes have been made!

2024-03-19 21:38 UTC, gfilicetti requested changes
See my Bump messages on review comments not addressed.

Looking great otherwise.

2024-03-19 21:38 UTC, gfilicetti commented on hacks/modernizing-monoliths/README.md
> +With your Docker image ready and tested, you are ready to get it running on GKE so players can start enjoying this retro-style rogue-like. Your manager asks that you try to keep the node sizes small
Bump.

2024-03-19 21:38 UTC, gfilicetti commented on hacks/modernizing-monoliths/README.md
> +- SSH into a game server container and check the files
Bump

2024-03-19 21:38 UTC, gfilicetti commented on hacks/modernizing-monoliths/README.md
> +- The load testing clients sometimes have connection issues, don't be concerned if GKE shows you have 100 pods running, but your application only shows a handful
Bump

2024-03-19 21:38 UTC, gfilicetti commented on hacks/modernizing-monoliths/README.md
> +- The load testing clients sometimes have connection issues, don't be concerned if GKE shows you have 100 pods running, but your application only shows a handful
Bump

2024-03-19 21:38 UTC, gfilicetti commented on hacks/modernizing-monoliths/README.md
> +- See bots logged into your game server and watch their session to see them playing the game
Bump

2024-03-19 21:38 UTC, gfilicetti commented on hacks/modernizing-monoliths/README.md
> +The install instructions:
Bump

2024-03-22 19:57 UTC, gfilicetti requested changes
Just one last thing Lance.... re: the Advanced challenge and the warning about the 25 min compile.

2024-03-22 19:57 UTC, gfilicetti commented on hacks/modernizing-monoliths/README.md
> +- **Compiling DCSS with `make WEBTILES=y` command can take 25+ minutes**. Compile the code on your host machine and create your image from the compiled code to save time on your builds.
Bump... 

I think you should move this out of Tips and as a "Note" inside of the advanced challenge. I don't want them getting confused that they might have to do this for the regular challenge.

2024-03-30 16:51 UTC, TheLanceLord commented
> Just one last thing Lance.... re: the Advanced challenge and the warning about the 25 min compile.

Moved! https://thelancelord.github.io/cloud-hackathons/hacks/modernizing-monoliths/challenge-01.html

2024-04-24 16:22 UTC, gfilicetti approved these changes

2024-04-24 16:23 UTC, merged