Updating the Gaming on Google Cloud gHack to use Space Agon
GoogleCloudPlatform/cloud-hackathons pull request #85
Opened 2024-04-24 21:03 UTC by TheLanceLord

Changes to the Cloud Gaming gHack, updating the readme, challenges, and solutions guide. The hack will now have participants deploying Space Agon with Agones and setting up Open Match.

Github Pages: https://thelancelord.github.io/cloud-hackathons/hacks/gaming-on-gcp/

2024-04-24 21:05 UTC, TheLanceLord commented
@gfilicetti @meken

2024-04-30 08:01 UTC, meken commented on hacks/gaming-on-gcp/README.md
>  - [Agones documentation](https://agones.dev/)
This seems to be a duplicate (although the urls are slightly different). Would it be an idea to make this list of learning resources shorter and more to the point?

2024-04-30 08:12 UTC, meken commented on hacks/gaming-on-gcp/README.md
> +git clone https://github.com/TheLanceLord/space-agon-ghack
Do we need to pass the exact command here? Can't we just provide a link and ask people to clone it?

2024-04-30 08:14 UTC, meken commented on hacks/gaming-on-gcp/README.md
> +docker push $REGISTRY/space-agon-frontend:0.1
Similar comment as above, do we need to spoon-feed this, instead of asking to build and push the image? (I'm okay if we're deliberately making this copy-paste, just want to make sure that it's a conscious choice)

2024-04-30 08:16 UTC, meken commented on hacks/gaming-on-gcp/README.md
> +- Demonstrate you can connect to your frontend via your Service’s IP address by using your browser to connect to http://<YOUR-FRONTEND-IP>.
You need to escape the URL, e.g. `http://<YOUR-FRONTEND-IP>`, the part after the protocol is not rendered properly right now

2024-04-30 08:17 UTC, meken commented on hacks/gaming-on-gcp/README.md
> +docker push $REGISTRY/space-agon-dedicated:0.1
Similar copy-paste content warning

2024-04-30 08:17 UTC, meken commented on hacks/gaming-on-gcp/README.md
> +- You are able to play a game of SpaceAgon with your team by first connecting to http://<YOUR-FRONTEND-IP> and then clicking `Connect to Server` and providing your GameServers IP address and port.
Escape the URL

2024-04-30 08:19 UTC, meken commented on hacks/gaming-on-gcp/README.md
> +> **Note** A Fleet is a managed set of Game Servers. Fleets manage Game Servers similar to how Deployments manage Pods.
This belongs in the Introduction section

2024-04-30 08:20 UTC, meken commented on hacks/gaming-on-gcp/README.md
> +- Demonstrate you can play a game on the allocated server by first connecting to http://<YOUR-FRONTEND-IP> and then clicking `Connect to Server` and providing your GameServers IP address and port. an
Escape URL

2024-04-30 08:21 UTC, meken commented on hacks/gaming-on-gcp/README.md
> +docker push $REGISTRY/space-agon-mmf:0.1
Similar copy-paste content warning

2024-04-30 08:21 UTC, meken commented on hacks/gaming-on-gcp/README.md
> +docker push $REGISTRY/space-agon-director:0.1
Similar copy-paste content warning

2024-04-30 12:12 UTC, gfilicetti commented on hacks/gaming-on-gcp/README.md
>  - [Agones documentation](https://agones.dev/)
+1 on a shorter list. I'd remove 

- the general K8S overview list.
- The general Agones doc
- Maybe the Zonal doc?

2024-04-30 12:13 UTC, gfilicetti commented on hacks/gaming-on-gcp/README.md
> +git clone https://github.com/TheLanceLord/space-agon-ghack
+1 here, they should know how to clone and this is the precedent we've set in other gHacks. Good for the coach's guide though.

2024-04-30 12:14 UTC, gfilicetti commented on hacks/gaming-on-gcp/README.md
> +docker push $REGISTRY/space-agon-frontend:0.1
Yeah the question is if we want them burning time finding (or coming up with the docker command). Question for @TheLanceLord .... are they exact commands in the Agones game server deploy documentation? If so, we might want to let them hunt for it with a note to coaches to not let them burn too much time.

2024-04-30 12:15 UTC, gfilicetti commented on hacks/gaming-on-gcp/README.md
> +- Demonstrate you can connect to your frontend via your Service’s IP address by using your browser to connect to http://<YOUR-FRONTEND-IP>.
Murat's suggestion is being rendered. He's saying to surround the sample URL with single back ticks

2024-04-30 12:46 UTC, gfilicetti requested changes
Great stuff here, comments are pretty minor. Amazing rescue of this gHack, brother.

2024-04-30 12:50 UTC, meken commented on hacks/gaming-on-gcp/solutions.md
This section is not needed in the solution guide

2024-04-30 12:56 UTC, meken commented on hacks/gaming-on-gcp/solutions.md
Put at the top the title as the top level header:
```
# Gaming on Google Cloud
```

2024-04-30 12:57 UTC, meken commented on hacks/gaming-on-gcp/solutions.md
I'd suggest to remove Objectives/Prereqs/Materials sections, remove the Suggested Steps header and put the solution as the body of the Notes & Guidance

2024-04-30 16:16 UTC, gfilicetti requested changes
Coaches guide looks good, just a few more suggestions here.

2024-04-30 16:16 UTC, gfilicetti commented on hacks/gaming-on-gcp/solutions.md
Yeah, remove the whole "Materials" section.

For the record, Daniel did not use the Coach Guide template as per the scaffolding, you're better off using your Monolith as a template.

2024-05-01 20:35 UTC, TheLanceLord commented on hacks/gaming-on-gcp/README.md
> +docker push $REGISTRY/space-agon-frontend:0.1
@meken @gfilicetti I lean towards making the Docker commands copy-paste. Because we aren't listing Docker knowledge as a pre-req for the hack, I can easily see people without experience burning 30+ minutes trying to figure this out and still not really understanding the code that they ran. We could add a note/callout though, something like:
"Unfamiliar with Docker and what this command is doing? After this gHack, check out Modernizing the Monolith: Containerizing and Deploying to Kubernetes to get hands-on experience with containerizing and deploying applications."

2024-05-01 20:45 UTC, gfilicetti commented on hacks/gaming-on-gcp/README.md
> +docker push $REGISTRY/space-agon-frontend:0.1
I love the call out, cross pollenating your own 2 gHacks. Brilliance.

@meken, what do you think?

2024-05-01 20:52 UTC, TheLanceLord commented on hacks/gaming-on-gcp/README.md
> +- Challenge 2: Deploy GameServers - Space Agon
The type in Agones is GameServer and from what I can see, their spec documentation uses the no space version, and even their Create a Game Server page has the description "This guide covers how you can quickly get started using Agones to create GameServers."

2024-05-01 21:43 UTC, gfilicetti commented on hacks/gaming-on-gcp/README.md
> +- Challenge 2: Deploy GameServers - Space Agon
Sounds good, I'm happy with that.

2024-05-02 13:33 UTC, meken commented on hacks/gaming-on-gcp/README.md
> +docker push $REGISTRY/space-agon-frontend:0.1
I love it!

2024-05-02 21:01 UTC, TheLanceLord commented
Changes should all be made, ready for another round of checks!

2024-05-02 21:16 UTC, gfilicetti reviewed
One last tiiiiiiiiiny thing

2024-05-02 21:16 UTC, gfilicetti commented on hacks/gaming-on-gcp/README.md
> +   > **Note** You must ALWAYS use `kubectl create` with the allocator.yaml file, `kubectl apply` will not work.
Unindent this to bring it inline with the Note on line 236, this way they render at the same level (and not at the level of the bullet list).

2024-05-03 11:53 UTC, meken approved these changes
Looks great! Thanks a lot for all the work you put into this!

2024-05-03 13:10 UTC, merged